### ISSUE TITLE
Some troubles when running main.py

### ISSUE THREAD

**Issue by zh-ouie** [hitarth64/DARWIN#1]
Hi, I was excited to see such a creative framework, but I ran into a few issues when replicating the code.Such when i run the `main.py`, an error `Exception has occurred: ImportError cannot import name 'MoleculesBondRester' from 'mp_api.client.routes.molecules.bonds' `  has occurred.when i check out the `bond.py` ,I found that the name of the class in the code was MoleculeBondRester.Is this a typo? Or if a newer version of the code is available. 
Looking forward to your reply.

**Comment by zh-ouie** [comment]
@hitarth64

**Comment by hitarth64** [comment]
Hi @zh-ouie . Thanks. This seems to be an error arising from mp_api ([this line](https://github.com/hitarth64/DARWIN/blob/e41b9e3fc8523b8a57a1be0aaa593fe8afcf3fb2/darwin/utils.py#L4)). Can you share which version of mp_api and pymatgen are you using?

**Comment by zh-ouie** [comment]
Hi @hitarth64 .The versions of mp-api and pymatgen  are shown in Figure.![image](https://github.com/hitarth64/DARWIN/assets/115514349/bc54e18a-3ffc-49fa-aa55-8cfe7ffe2ab7)
![image](https://github.com/hitarth64/DARWIN/assets/115514349/6a3342e6-e576-42c2-b0e4-facda0ab97a3)

**Comment by hitarth64** [comment]
Can you also paste the detailed error message you encounter when you try to run main.py?

**Comment by zh-ouie** [comment]
What details do you need? This is a vscode error when running the program.![image](https://github.com/hitarth64/DARWIN/assets/115514349/cd49aaab-6e8b-4db1-8001-cbb9dc06366e)

**Comment by hitarth64** [comment]
This seems very much an mp_api problem. We can try to troubleshoot it though. 

1. Can you try to run  just`from mp_api.client import MPRester`? If you see the same error, that means the problem is due to mp_api.

2. To fix it, can you try to force reinstall mp_api. The latest version is 0.34.2. You can do this by - `pip install mp-api --upgrade`

**Comment by zh-ouie** [comment]
Thank you very much! It was an mp-api versioning issue, and it's now fixed.
